### ISSUE TITLE
vuetify+nuxt+vue-macros combination of components has stopped working

### ISSUE THREAD

**Issue by AndreyKindin** [vuetifyjs/nuxt-module#275]
Hello, 
recently, the combination of vuetify+nuxt(-module)+vue-macros stopped working. 
If I remove Vue macros from the module, it seems to work. I'm not sure if I'm in the right place with the bug, but maybe just as a heads up that the bug exists.
Here is the Stackblitz for it:
https://stackblitz.com/edit/nuxt-starter-5xyynj?file=nuxt.config.ts

P.S.:
If I try to implement the whole thing without the vuetify-nuxt-module, but rather via the plugin, I get the error:
Cannot start nuxt:  Vuetify plugin must be loaded after the vue plugin                                     

  at configResolved (node_modules/vite-plugin-vuetify/dist/index.cjs:29:15)
  at node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:66327:67
  at Array.map (<anonymous>)
  at resolveConfig (node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:66327:53)
  at async _createServer (node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:62687:18)
  at async buildClient (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.CMaRZVaO.mjs:745:24)
  at async withLogs (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.CMaRZVaO.mjs:1835:3)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.CMaRZVaO.mjs:1826:3)
  at async bundle (node_modules/nuxt/dist/index.mjs:5888:5)
  at async build (node_modules/nuxt/dist/index.mjs:5763:3)

**Comment by userquin** [comment]
looks like something wrong in `@vue-macros/nuxt`, I'm going to try to fix it

**Comment by userquin** [comment]
`@vue-macros/nuxt` removing `vite:vue` plugin https://github.com/vue-macros/vue-macros/blob/main/packages/nuxt/src/index.ts#L41-L42, I'll send you a module to fix the problem and maybe detect `@vue-macros/nuxt` module here to move the internal plugins.

**Comment by userquin** [comment]
@AndreyKindin check my comment on vue macros issue

**Comment by userquin** [comment]
@AndreyKindin check https://stackblitz.com/edit/nuxt-starter-jq6cno?file=nuxt.config.ts,app.vue,package.json,.nuxt%2Fcomponents.d.ts again

It is using the pkg-pr-new from this PR https://github.com/vuetifyjs/nuxt-module/pull/276 and it is working since there is no dependency on `vite:vue`  plugin => moved to Nuxt auto import

I need to add directove to Nuxt and we can remove custom Vuetify Vite plugin here: rn only used for directives ignoring any component or lab component auto import

**Comment by sxzz** [comment]
The reason is that Vue Macros will remove `vite:vue` plugin from the original plugin list and add it back into an array.

before: `[a, 'vite:vue', b]`
after: `[a, [b, 'vite:vue', c, d], e]`
now: `[a, b, 'vite:vue', c, d, e]`

This way it won't affect other plugins. Successfully fixed at https://stackblitz.com/edit/nuxt-starter-itabzd.

**Comment by userquin** [comment]
thx @sxzz ❤️

**Comment by AndreyYolkin** [comment]
Fixed upstream in `@vue-macros`. The root cause was Vue Macros removing `vite:vue` from the plugin list and re-inserting it inside a nested array, which broke plugin ordering (`Vuetify plugin must be loaded after the vue plugin`). @sxzz fixed this in Vue Macros so the reinserted `vite:vue` no longer affects other plugins' positions (confirmed in the thread above, Sep 2024). A current `@vue-macros/nuxt` resolves the conflict with no changes needed in this module.

(Note: PR #276 — moving directive/component handling to the Nuxt components loader — is a separate breaking refactor tied to the upcoming rewrite, not required for this fix; it stays open on its own track.)

Closing as resolved upstream. Please reopen if it still reproduces with a recent `@vue-macros/nuxt`.
