### ISSUE TITLE
KO installation on an existing project

### ISSUE THREAD

**Issue by kaboume** [vuetifyjs/nuxt-module#287]
I have a Nuxt 3.x project that I started over a year ago and that worked with the vite vuetify plugin.
I wanted to install this module instead but when I run the command:

npx nuxi@latest module add vuetify-nuxt-module

I have a series of errors like this:

```
npx nuxi@latest module add vuetify-nuxt-module
ℹ Installing vuetify-nuxt-module@latest development dependency                                            09:59:24
 WARN  GET https://registry.npmjs.org/vuetify-nuxt-module error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@antfu%2Feslint-config error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@iconify-json%2Fcarbon error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@iconify-json%2Ftwemoji error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@iconify%2Fvue error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@nuxtjs%2Fsitemap error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@sidebase%2Fnuxt-auth error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@vue-leaflet%2Fvue-leaflet error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/eslint error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.     
 WARN  GET https://registry.npmjs.org/leaflet error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.    
 WARN  GET https://registry.npmjs.org/nuxt error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.       
 WARN  GET https://registry.npmjs.org/pinia error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.      
 WARN  GET https://registry.npmjs.org/sass error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.       
 WARN  GET https://registry.npmjs.org/typescript error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left. 
 WARN  GET https://registry.npmjs.org/@googlemaps%2Fjs-api-loader error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@mdi%2Ffont error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/vuetify-nuxt-module error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@antfu%2Feslint-config error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@iconify-json%2Fcarbon error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@iconify-json%2Ftwemoji error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@iconify%2Fvue error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@nuxtjs%2Fsitemap error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@sidebase%2Fnuxt-auth error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@vue-leaflet%2Fvue-leaflet error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/eslint error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.       
 WARN  GET https://registry.npmjs.org/leaflet error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.      
 WARN  GET https://registry.npmjs.org/nuxt error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/pinia error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.        
 WARN  GET https://registry.npmjs.org/sass error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/typescript error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.   
 WARN  GET https://registry.npmjs.org/@googlemaps%2Fjs-api-loader error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@mdi%2Ffont error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.  
 WARN  GET https://registry.npmjs.org/@pinia-plugin-persistedstate%2Fnuxt error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/vuetify-nuxt-module: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmjs.org/@pinia%2Fnuxt error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@vuepic%2Fvue-datepicker error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/add-to-calendar-button error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/filesize error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.   
 WARN  GET https://registry.npmjs.org/get-video-id error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.

 ERROR  Command failed with exit code 1: corepack pnpm add -D vuetify-nuxt-module@latest                   10:00:34  

  at makeError (/C:/Users/ericm/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/index7.mjs:626:11)
  at handlePromise (/C:/Users/ericm/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/index7.mjs:1552:26)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async executeCommand (/C:/Users/ericm/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.e773be50.mjs:43:3)
  at async addDependency (/C:/Users/ericm/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.e773be50.mjs:208:3)
  at async Object.setup (/C:/Users/ericm/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/add2.mjs:151:19)
  at async runCommand$1 (/C:/Users/ericm/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1620:5)
  at async runCommand$1 (/C:/Users/ericm/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runCommand$1 (/C:/Users/ericm/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runMain$1 (/C:/Users/ericm/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7)

❯ Install failed for vuetify-nuxt-module@latest. Do you want to continue adding the module to nuxt.config?
○ Yes / ● No
```

What I don't understand is that I have other projects on my laptop that I started more recently with this plugin and no problem.

**Comment by kaboume** [comment]
Nuxt project info:                                                                                         10:06:43

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.15.0
- Nuxt Version:     ^3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @pinia/nuxt@^0.5.1, @pinia-plugin-persistedstate/nuxt@^1.2.0, @sidebase/nuxt-auth@^0.5.0, @nuxtjs/sitemap@^6.1.2, vuetify-nuxt-module@^0.18.3
- Build Modules:    -
------------------------------

**Comment by nboyet** [comment]
@kaboume, the interesting log is the following : "ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/vuetify-nuxt-module: Value of "this" must be of type URLSearchParams"
According to this discussion : https://github.com/pnpm/pnpm/issues/6424, it is probably coming from your pnpm/action-setup version

**Comment by AndreyYolkin** [comment]
This isn't a bug in `vuetify-nuxt-module` — it's an upstream tooling issue.

The key line is:

```
ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/vuetify-nuxt-module: Value of "this" must be of type URLSearchParams
ERROR  Command failed with exit code 1: corepack pnpm add -D vuetify-nuxt-module@latest
```

`ERR_INVALID_THIS` / `Value of "this" must be of type URLSearchParams` is a known bug in **older pnpm versions** running on recent Node (an undici regression): pnpm/pnpm#6424.

What happens here is that `nuxi module add` shells out to `corepack pnpm add`, and corepack pins/uses an old pnpm version (not the pnpm you have installed) which trips that bug. That part is tracked in nuxt/cli#916. It explains why your other, newer projects work fine — different resolved pnpm version.

**Workarounds:**
- Update pnpm: `pnpm self-update` / `corepack prepare pnpm@latest --activate`, or
- Bypass corepack and add the dep with your own package manager directly, e.g. `npm i -D vuetify-nuxt-module` (or `pnpm add -D vuetify-nuxt-module` with an up-to-date pnpm), then add the module to `nuxt.config`.

Closing as upstream — nothing to fix on the module side. See pnpm/pnpm#6424 and nuxt/cli#916 for the actual fixes.
